// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDro94aitaF1Dck6xRdElpgw8CCjF0Ezoc',
    appId: '1:1029784256621:web:c912702de8bf2782cebf64',
    messagingSenderId: '1029784256621',
    projectId: 'kizen-da39f',
    authDomain: 'kizen-da39f.firebaseapp.com',
    storageBucket: 'kizen-da39f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOpTsRPHgFEMvZaj4NzXENAQoMh5UbGss',
    appId: '1:1029784256621:android:dbdb8f1e8d9dfad1cebf64',
    messagingSenderId: '1029784256621',
    projectId: 'kizen-da39f',
    storageBucket: 'kizen-da39f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb5Rp9Oxc982c6o322qFuPalqsfnwsaJE',
    appId: '1:1029784256621:ios:bffb8ba118a531b0cebf64',
    messagingSenderId: '1029784256621',
    projectId: 'kizen-da39f',
    storageBucket: 'kizen-da39f.firebasestorage.app',
    iosBundleId: 'com.reikypratama.aplikasiKomik',
  );
}
